services:
  redis:
    image: redis:7.4.9
    profiles: [pandora]
    networks: [app_network]
    restart: unless-stopped

  kvrocks:
    image: apache/kvrocks:2.15.0
    profiles: [pandora]
    networks: [app_network]
    restart: unless-stopped

  clamav:
    image: clamav/clamav:1.5.2
    profiles: [pandora]
    volumes:
      - clamav-socket:/var/run/clamav
      - ./docker/pandora/config/clamav/clamd.conf:/etc/clamav/clamd.conf:ro
      - ./docker/pandora/config/clamav/freshclam.conf:/etc/clamav/freshclam.conf:ro
    networks: [app_network]
    environment:
    - HTTP_PROXY=${PROXY}
    - HTTPS_PROXY=${PROXY}
    - http_proxy=${PROXY}
    - https_proxy=${PROXY}
    healthcheck:
      test: ["CMD", "clamdscan", "--ping", "1"]
      start_period: 180s
      interval:     30s
      timeout:      5s
      retries:      3
    restart: unless-stopped

  pandora:
    image: ghcr.io/pandora-analysis/pandora:v1.12.2
    profiles: [pandora]
    depends_on: [redis, kvrocks, clamav]
    expose: ["6100"]
    environment:
      - PANDORA_REDIS_HOST=redis
      - PANDORA_KVROCKS_HOST=kvrocks
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
      - http_proxy=${PROXY}
      - https_proxy=${PROXY}
    working_dir: /pandora
    tty: true
    command:
      - /bin/sh
      - -c
      - |
          echo "[pandora] waiting for dependencies..."
          sleep 60
          echo "[pandora] starting service"
          poetry run start
          tail -F ./LICENSE
    env_file:
      - ./docker/pandora/pandora.env
    volumes:
      - pandora_cache:/pandora/cache
      - pandora_storage:/pandora/storage
      - clamav-socket:/var/run/clamav
      - ./docker/pandora/config/generic.json:/pandora/config/generic.json:ro
      - ./docker/pandora/workers:/pandora/pandora/workers:ro
      - ./docker/pandora/yara_rules:/pandora/yara_rules:ro
    networks: [app_network]
    restart: unless-stopped

volumes:
  pandora_cache:
  pandora_storage:
  clamav-socket:
